name: ramadanplanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^5.0.0-release-candidate-6
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^6.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hijri: ^3.0.0
  permission_handler: ^11.0.1  
  firebase_core: ^2.6.1
  flutter_local_notifications: ^17.2.2
  daynightbanner: ^0.0.2
  adhan: ^2.0.0+1
  intl: ^0.18.1
  animated_notch_bottom_bar: ^1.0.3
  flutter_svg: ^2.0.10+1
  home_widget: ^0.7.0
  flutter_qiblah: ^3.0.3
  geolocator: ^11.1.0
 
 


  # firebase_messaging: ^14.3.0
  # firebase_crashlytics: ^3.0.17

  

dev_dependencies: 
  flutter_lints: ^3.0.1   
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icon/
    - assets/json/
    - assets/sound/notification.mp3
    
  uses-material-design: true

  fonts: 
    - family: Li
      fonts: 
        - asset: assets/font/Li.ttf
          weight: 700
    - family: Tuli
      fonts: 
        - asset: assets/font/Tuli.ttf
          weight: 400
    - family: Lato
      fonts: 
        - asset: assets/font/Lato-Regular.ttf
          weight: 400
    
    - family: arbi
      fonts: 
        - asset: assets/font/arbi.ttf
          weight: 400
    
