name: ramadanplanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^4.0.3
  pie_chart: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hijri: ^3.0.0
  awesome_notifications: ^0.7.4+1
  permission_handler: ^10.2.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/json/
    - assets/sound/notification.mp3
    
  uses-material-design: true

  fonts: 
    - family: Li
      fonts: 
        - asset: assets/font/Li.ttf
          weight: 700
    - family: Tuli
      fonts: 
        - asset: assets/font/Tuli.ttf
          weight: 400
    - family: Lato
      fonts: 
        - asset: assets/font/Lato-Regular.ttf
          weight: 400
    
    - family: arbi
      fonts: 
        - asset: assets/font/arbi.ttf
          weight: 400
    
