// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3PdiKy1RBlnq7-2DGgC84zP-ER4_d_s',
    appId: '1:377917129946:web:0794dbae835b45658951e3',
    messagingSenderId: '377917129946',
    projectId: 'ramadanplanner2024',
    authDomain: 'ramadanplanner2024.firebaseapp.com',
    storageBucket: 'ramadanplanner2024.appspot.com',
    measurementId: 'G-LV4PTW80PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf49C2RanI2sN-F32Uc-4M6xD73Anq1r4',
    appId: '1:377917129946:android:e426a59e9606c2b88951e3',
    messagingSenderId: '377917129946',
    projectId: 'ramadanplanner2024',
    storageBucket: 'ramadanplanner2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZKkqcKjlG6iu8002zVrGHtehXCPaJ-U0',
    appId: '1:377917129946:ios:bbe9a7e6f9cfe1cc8951e3',
    messagingSenderId: '377917129946',
    projectId: 'ramadanplanner2024',
    storageBucket: 'ramadanplanner2024.appspot.com',
    iosBundleId: 'com.ababildev.ramadanplanner',
  );
}
