// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U6xN8mASwR5Qa0SR6WT4gs58BjjiRJg',
    appId: '1:123081775898:web:8407066bc5eb1f158a6aa3',
    messagingSenderId: '123081775898',
    projectId: 'ramadanplannerbd',
    authDomain: 'ramadanplannerbd.firebaseapp.com',
    storageBucket: 'ramadanplannerbd.appspot.com',
    measurementId: 'G-0RB8B28120',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l4HwLkylYvk7_9P0aQk95zGXv4lbGFQ',
    appId: '1:123081775898:android:3790bdec5a64dec58a6aa3',
    messagingSenderId: '123081775898',
    projectId: 'ramadanplannerbd',
    storageBucket: 'ramadanplannerbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVhmublVOOxovziiXqbwonZvGnKJVESaU',
    appId: '1:123081775898:ios:14596f687d7ec5058a6aa3',
    messagingSenderId: '123081775898',
    projectId: 'ramadanplannerbd',
    storageBucket: 'ramadanplannerbd.appspot.com',
    iosBundleId: 'com.ababildev.ramadanplanner',
  );
}
